### ISSUE TITLE
thestartuppitch.com stole my credit card

### ISSUE THREAD

**Issue by backmeupplz** [mmccaff/PlacesToPostYourStartup#99]
Please, remove it from the list.

**Comment by mmccaff** [comment]
Was this resolved @backmeupplz ? I figured I'd wait a few days and ask before deleting it.

**Comment by backmeupplz** [comment]
@mmccaff oh, my bank blocked the malicious transaction fortunately :) had to get my credit card reissued though. Transaction time on this credit card was on the same day as when I used it on the website there. And I didn't use that credit card anywhere else.

Leaving it up to you to figure this out :) If you need any extra info, let me know. Cheers!

**Comment by mmccaff** [comment]
I removed it from the list. Thanks @backmeupplz !
